// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealFenixFailures.Infrastructure.Persistence;

#nullable disable

namespace RealFenixFailures.Infrastructure.Migrations
{
    [DbContext(typeof(RealFenixDbContext))]
    [Migration("20260522094635_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("PresetFailureDefinition", b =>
                {
                    b.Property<int>("FailureDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailurePresetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FailureDefinitionId", "FailurePresetId");

                    b.HasIndex("FailurePresetId");

                    b.ToTable("PresetFailureDefinition");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FailurePreset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("PresetType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FailurePresets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Fallas menores iniciales para forzar checklist real.",
                            Name = "Cold & Dark Immersion",
                            PresetType = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Fallas aleatorias menores durante el vuelo.",
                            Name = "Random Non-Critical",
                            PresetType = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fallas aleatorias con posibilidad de fallas críticas.",
                            Name = "Random with Critical",
                            PresetType = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Fallas críticas por fase para entrenamiento.",
                            Name = "Training Mode",
                            PresetType = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "Distribución cercana a operación real A320.",
                            Name = "Realistic Mode",
                            PresetType = 5
                        },
                        new
                        {
                            Id = 6,
                            Description = "Preset vacío para reglas del usuario.",
                            Name = "Custom",
                            PresetType = 6
                        });
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FenixFailureDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FenixFailureId")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FenixFailureId")
                        .IsUnique();

                    b.HasIndex("GroupId");

                    b.ToTable("FenixFailureDefinitions");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FenixFailureGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SystemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SystemId");

                    b.ToTable("FenixFailureGroups");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FenixFailureSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FenixFailureSystems");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FlightSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PresetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PresetId");

                    b.ToTable("FlightSessions");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.TriggeredFailure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FailureDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightPhase")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PresetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("TriggeredAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FailureDefinitionId");

                    b.HasIndex("FlightSessionId");

                    b.HasIndex("PresetId");

                    b.ToTable("TriggeredFailures");
                });

            modelBuilder.Entity("PresetFailureDefinition", b =>
                {
                    b.HasOne("RealFenixFailures.Domain.Entities.FenixFailureDefinition", null)
                        .WithMany()
                        .HasForeignKey("FailureDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealFenixFailures.Domain.Entities.FailurePreset", null)
                        .WithMany()
                        .HasForeignKey("FailurePresetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FenixFailureDefinition", b =>
                {
                    b.HasOne("RealFenixFailures.Domain.Entities.FenixFailureGroup", "Group")
                        .WithMany("FailureDefinitions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FenixFailureGroup", b =>
                {
                    b.HasOne("RealFenixFailures.Domain.Entities.FenixFailureSystem", "System")
                        .WithMany("FailureGroups")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("System");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FlightSession", b =>
                {
                    b.HasOne("RealFenixFailures.Domain.Entities.FailurePreset", "Preset")
                        .WithMany()
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Preset");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.TriggeredFailure", b =>
                {
                    b.HasOne("RealFenixFailures.Domain.Entities.FenixFailureDefinition", "FailureDefinition")
                        .WithMany()
                        .HasForeignKey("FailureDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RealFenixFailures.Domain.Entities.FlightSession", "FlightSession")
                        .WithMany("TriggeredFailures")
                        .HasForeignKey("FlightSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealFenixFailures.Domain.Entities.FailurePreset", "Preset")
                        .WithMany()
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FailureDefinition");

                    b.Navigation("FlightSession");

                    b.Navigation("Preset");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FenixFailureGroup", b =>
                {
                    b.Navigation("FailureDefinitions");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FenixFailureSystem", b =>
                {
                    b.Navigation("FailureGroups");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FlightSession", b =>
                {
                    b.Navigation("TriggeredFailures");
                });
#pragma warning restore 612, 618
        }
    }
}
