// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealFenixFailures.Infrastructure.Persistence;

#nullable disable

namespace RealFenixFailures.Infrastructure.Migrations
{
    [DbContext(typeof(RealFenixDbContext))]
    [Migration("20260518165007_AddExternalFailureId")]
    partial class AddExternalFailureId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("PresetFailureDefinition", b =>
                {
                    b.Property<Guid>("FailureDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FailurePresetId")
                        .HasColumnType("TEXT");

                    b.HasKey("FailureDefinitionId", "FailurePresetId");

                    b.HasIndex("FailurePresetId");

                    b.ToTable("PresetFailureDefinition");

                    b.HasData(
                        new
                        {
                            FailureDefinitionId = new Guid("c13afc03-95e4-439f-b464-95ce3a7e1001"),
                            FailurePresetId = new Guid("08fcd6c9-0e35-4a28-86e5-4ab78a4cc001")
                        },
                        new
                        {
                            FailureDefinitionId = new Guid("c13afc03-95e4-439f-b464-95ce3a7e1002"),
                            FailurePresetId = new Guid("08fcd6c9-0e35-4a28-86e5-4ab78a4cc001")
                        },
                        new
                        {
                            FailureDefinitionId = new Guid("c13afc03-95e4-439f-b464-95ce3a7e1001"),
                            FailurePresetId = new Guid("08fcd6c9-0e35-4a28-86e5-4ab78a4cc002")
                        },
                        new
                        {
                            FailureDefinitionId = new Guid("c13afc03-95e4-439f-b464-95ce3a7e1002"),
                            FailurePresetId = new Guid("08fcd6c9-0e35-4a28-86e5-4ab78a4cc002")
                        },
                        new
                        {
                            FailureDefinitionId = new Guid("c13afc03-95e4-439f-b464-95ce3a7e1003"),
                            FailurePresetId = new Guid("08fcd6c9-0e35-4a28-86e5-4ab78a4cc002")
                        },
                        new
                        {
                            FailureDefinitionId = new Guid("c13afc03-95e4-439f-b464-95ce3a7e1004"),
                            FailurePresetId = new Guid("08fcd6c9-0e35-4a28-86e5-4ab78a4cc002")
                        },
                        new
                        {
                            FailureDefinitionId = new Guid("c13afc03-95e4-439f-b464-95ce3a7e1003"),
                            FailurePresetId = new Guid("08fcd6c9-0e35-4a28-86e5-4ab78a4cc003")
                        },
                        new
                        {
                            FailureDefinitionId = new Guid("c13afc03-95e4-439f-b464-95ce3a7e1004"),
                            FailurePresetId = new Guid("08fcd6c9-0e35-4a28-86e5-4ab78a4cc003")
                        },
                        new
                        {
                            FailureDefinitionId = new Guid("c13afc03-95e4-439f-b464-95ce3a7e1005"),
                            FailurePresetId = new Guid("08fcd6c9-0e35-4a28-86e5-4ab78a4cc003")
                        },
                        new
                        {
                            FailureDefinitionId = new Guid("c13afc03-95e4-439f-b464-95ce3a7e1006"),
                            FailurePresetId = new Guid("08fcd6c9-0e35-4a28-86e5-4ab78a4cc003")
                        },
                        new
                        {
                            FailureDefinitionId = new Guid("c13afc03-95e4-439f-b464-95ce3a7e1007"),
                            FailurePresetId = new Guid("08fcd6c9-0e35-4a28-86e5-4ab78a4cc003")
                        },
                        new
                        {
                            FailureDefinitionId = new Guid("c13afc03-95e4-439f-b464-95ce3a7e1007"),
                            FailurePresetId = new Guid("08fcd6c9-0e35-4a28-86e5-4ab78a4cc004")
                        },
                        new
                        {
                            FailureDefinitionId = new Guid("c13afc03-95e4-439f-b464-95ce3a7e1005"),
                            FailurePresetId = new Guid("08fcd6c9-0e35-4a28-86e5-4ab78a4cc004")
                        },
                        new
                        {
                            FailureDefinitionId = new Guid("c13afc03-95e4-439f-b464-95ce3a7e1006"),
                            FailurePresetId = new Guid("08fcd6c9-0e35-4a28-86e5-4ab78a4cc004")
                        },
                        new
                        {
                            FailureDefinitionId = new Guid("c13afc03-95e4-439f-b464-95ce3a7e1008"),
                            FailurePresetId = new Guid("08fcd6c9-0e35-4a28-86e5-4ab78a4cc004")
                        },
                        new
                        {
                            FailureDefinitionId = new Guid("c13afc03-95e4-439f-b464-95ce3a7e1001"),
                            FailurePresetId = new Guid("08fcd6c9-0e35-4a28-86e5-4ab78a4cc005")
                        },
                        new
                        {
                            FailureDefinitionId = new Guid("c13afc03-95e4-439f-b464-95ce3a7e1002"),
                            FailurePresetId = new Guid("08fcd6c9-0e35-4a28-86e5-4ab78a4cc005")
                        },
                        new
                        {
                            FailureDefinitionId = new Guid("c13afc03-95e4-439f-b464-95ce3a7e1003"),
                            FailurePresetId = new Guid("08fcd6c9-0e35-4a28-86e5-4ab78a4cc005")
                        },
                        new
                        {
                            FailureDefinitionId = new Guid("c13afc03-95e4-439f-b464-95ce3a7e1004"),
                            FailurePresetId = new Guid("08fcd6c9-0e35-4a28-86e5-4ab78a4cc005")
                        },
                        new
                        {
                            FailureDefinitionId = new Guid("c13afc03-95e4-439f-b464-95ce3a7e1005"),
                            FailurePresetId = new Guid("08fcd6c9-0e35-4a28-86e5-4ab78a4cc005")
                        },
                        new
                        {
                            FailureDefinitionId = new Guid("c13afc03-95e4-439f-b464-95ce3a7e1006"),
                            FailurePresetId = new Guid("08fcd6c9-0e35-4a28-86e5-4ab78a4cc005")
                        },
                        new
                        {
                            FailureDefinitionId = new Guid("c13afc03-95e4-439f-b464-95ce3a7e1007"),
                            FailurePresetId = new Guid("08fcd6c9-0e35-4a28-86e5-4ab78a4cc005")
                        },
                        new
                        {
                            FailureDefinitionId = new Guid("c13afc03-95e4-439f-b464-95ce3a7e1008"),
                            FailurePresetId = new Guid("08fcd6c9-0e35-4a28-86e5-4ab78a4cc005")
                        });
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FailureDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AffectedSystem")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("ApplicableFlightPhase")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalFailureId")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<double>("Probability")
                        .HasColumnType("REAL");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FailureDefinitions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c13afc03-95e4-439f-b464-95ce3a7e1001"),
                            AffectedSystem = "Cabin",
                            ApplicableFlightPhase = 1,
                            ExternalFailureId = "F_PNEUMATIC_CPC_1",
                            Name = "Cabin Light Burnout",
                            Probability = 0.23000000000000001,
                            Severity = 1
                        },
                        new
                        {
                            Id = new Guid("c13afc03-95e4-439f-b464-95ce3a7e1002"),
                            AffectedSystem = "AirConditioning",
                            ApplicableFlightPhase = 1,
                            ExternalFailureId = "F_PNEUMATIC_PACK_1_OVERHEAT",
                            Name = "Cabin Temp Sensor Out of Range",
                            Probability = 0.17999999999999999,
                            Severity = 1
                        },
                        new
                        {
                            Id = new Guid("c13afc03-95e4-439f-b464-95ce3a7e1003"),
                            AffectedSystem = "Electrical",
                            ApplicableFlightPhase = 5,
                            ExternalFailureId = "F_ELEC_AC_ESS_FEED_1",
                            Name = "Galley Bus Intermittent",
                            Probability = 0.14000000000000001,
                            Severity = 1
                        },
                        new
                        {
                            Id = new Guid("c13afc03-95e4-439f-b464-95ce3a7e1004"),
                            AffectedSystem = "Avionics",
                            ApplicableFlightPhase = 5,
                            ExternalFailureId = "F_FMGC_1",
                            Name = "Secondary Avionics Degraded",
                            Probability = 0.10000000000000001,
                            Severity = 2
                        },
                        new
                        {
                            Id = new Guid("c13afc03-95e4-439f-b464-95ce3a7e1005"),
                            AffectedSystem = "Pneumatics",
                            ApplicableFlightPhase = 4,
                            ExternalFailureId = "F_PNEUMATIC_TRIM_AIR",
                            Name = "PACK Fault",
                            Probability = 0.080000000000000002,
                            Severity = 2
                        },
                        new
                        {
                            Id = new Guid("c13afc03-95e4-439f-b464-95ce3a7e1006"),
                            AffectedSystem = "Hydraulics",
                            ApplicableFlightPhase = 6,
                            ExternalFailureId = "F_HYD_LOW_GREEN",
                            Name = "Hydraulic Low Pressure",
                            Probability = 0.040000000000000001,
                            Severity = 3
                        },
                        new
                        {
                            Id = new Guid("c13afc03-95e4-439f-b464-95ce3a7e1007"),
                            AffectedSystem = "Engine",
                            ApplicableFlightPhase = 3,
                            ExternalFailureId = "F_OH_FIRE_ENG_1",
                            Name = "Engine Fire Warning",
                            Probability = 0.02,
                            Severity = 3
                        },
                        new
                        {
                            Id = new Guid("c13afc03-95e4-439f-b464-95ce3a7e1008"),
                            AffectedSystem = "IceProtection",
                            ApplicableFlightPhase = 7,
                            ExternalFailureId = "F_PNEUMATIC_WAI_1",
                            Name = "Wing Anti-Ice Valve Fault",
                            Probability = 0.059999999999999998,
                            Severity = 2
                        });
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FailurePreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("PresetType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FailurePresets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("08fcd6c9-0e35-4a28-86e5-4ab78a4cc001"),
                            Description = "Fallas menores iniciales para forzar checklist real.",
                            Name = "Cold & Dark Immersion",
                            PresetType = 1
                        },
                        new
                        {
                            Id = new Guid("08fcd6c9-0e35-4a28-86e5-4ab78a4cc002"),
                            Description = "Fallas aleatorias menores durante el vuelo.",
                            Name = "Random Non-Critical",
                            PresetType = 2
                        },
                        new
                        {
                            Id = new Guid("08fcd6c9-0e35-4a28-86e5-4ab78a4cc003"),
                            Description = "Fallas aleatorias con posibilidad de fallas críticas.",
                            Name = "Random with Critical",
                            PresetType = 3
                        },
                        new
                        {
                            Id = new Guid("08fcd6c9-0e35-4a28-86e5-4ab78a4cc004"),
                            Description = "Fallas críticas por fase para entrenamiento.",
                            Name = "Training Mode",
                            PresetType = 4
                        },
                        new
                        {
                            Id = new Guid("08fcd6c9-0e35-4a28-86e5-4ab78a4cc005"),
                            Description = "Distribución cercana a operación real A320.",
                            Name = "Realistic Mode",
                            PresetType = 5
                        },
                        new
                        {
                            Id = new Guid("08fcd6c9-0e35-4a28-86e5-4ab78a4cc006"),
                            Description = "Preset vacío para reglas del usuario.",
                            Name = "Custom",
                            PresetType = 6
                        });
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FlightSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PresetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PresetId");

                    b.ToTable("FlightSessions");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.TriggeredFailure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FailureDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("FlightPhase")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FlightSessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PresetId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TriggeredAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FailureDefinitionId");

                    b.HasIndex("FlightSessionId");

                    b.HasIndex("PresetId");

                    b.ToTable("TriggeredFailures");
                });

            modelBuilder.Entity("PresetFailureDefinition", b =>
                {
                    b.HasOne("RealFenixFailures.Domain.Entities.FailureDefinition", null)
                        .WithMany()
                        .HasForeignKey("FailureDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealFenixFailures.Domain.Entities.FailurePreset", null)
                        .WithMany()
                        .HasForeignKey("FailurePresetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FlightSession", b =>
                {
                    b.HasOne("RealFenixFailures.Domain.Entities.FailurePreset", "Preset")
                        .WithMany()
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Preset");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.TriggeredFailure", b =>
                {
                    b.HasOne("RealFenixFailures.Domain.Entities.FailureDefinition", "FailureDefinition")
                        .WithMany()
                        .HasForeignKey("FailureDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RealFenixFailures.Domain.Entities.FlightSession", "FlightSession")
                        .WithMany("TriggeredFailures")
                        .HasForeignKey("FlightSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealFenixFailures.Domain.Entities.FailurePreset", "Preset")
                        .WithMany()
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FailureDefinition");

                    b.Navigation("FlightSession");

                    b.Navigation("Preset");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FlightSession", b =>
                {
                    b.Navigation("TriggeredFailures");
                });
#pragma warning restore 612, 618
        }
    }
}
