// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealFenixFailures.Infrastructure.Persistence;

#nullable disable

namespace RealFenixFailures.Infrastructure.Migrations
{
    [DbContext(typeof(RealFenixDbContext))]
    [Migration("20260714075414_DBChanges")]
    partial class DBChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.AircraftSystemWear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserAircraftId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("WearPercentage")
                        .HasColumnType("REAL");

                    b.Property<int>("WearableSystemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WearableSystemId");

                    b.HasIndex("UserAircraftId", "WearableSystemId")
                        .IsUnique();

                    b.ToTable("AircraftSystemWears");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.AircraftWearableSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AircraftWearableSystems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Engine 1",
                            ShortName = "ENG1"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Engine 2",
                            ShortName = "ENG2"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Hydraulic System",
                            ShortName = "HYD"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Landing Gear",
                            ShortName = "GEAR"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Navigation Systems",
                            ShortName = "NAV"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Pneumatic System",
                            ShortName = "PNEU"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "APU",
                            ShortName = "APU"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Doors",
                            ShortName = "DOOR"
                        });
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FailurePreset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightPhase")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("PresetType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PresetTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PresetType");

                    b.Property<string>("TriggerDescription")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PresetTypeId");

                    b.ToTable("FailurePresets", t =>
                        {
                            t.Property("PresetType")
                                .HasColumnName("PresetType1");
                        });
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FenixFailureDefinition", b =>
                {
                    b.Property<string>("FenixFailureId")
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.HasKey("FenixFailureId");

                    b.HasIndex("GroupId");

                    b.ToTable("FenixFailureDefinitions");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FenixFailureGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SystemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SystemId");

                    b.ToTable("FenixFailureGroups");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FenixFailureSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FenixFailureSystems");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FlightSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserAircraftId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserAircraftId");

                    b.ToTable("FlightSessions");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.PresetFailureDefinition", b =>
                {
                    b.Property<int>("PresetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FenixFailureId")
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<string>("Above_Altitude")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("AfterEvent")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("AfterEventSeconds")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Below_Altitude")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ias")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<double>("Probability")
                        .HasColumnType("REAL");

                    b.Property<int?>("ProbabilityGroup")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Time")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("PresetId", "FenixFailureId");

                    b.HasIndex("FenixFailureId");

                    b.ToTable("PresetFailureDefinitions");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.PresetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FailurePresetTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "RealisticMode"
                        },
                        new
                        {
                            Id = 2,
                            Description = "TrainingMode"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Custom"
                        },
                        new
                        {
                            Id = 4,
                            Description = "UserPreset"
                        });
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.TriggeredFailure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FenixFailureId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FlightPhase")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("TriggeredAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FenixFailureId");

                    b.HasIndex("FlightSessionId");

                    b.ToTable("TriggeredFailures");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.UserAircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("IcaoTypeCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<double>("TotalFlightHours")
                        .HasColumnType("REAL");

                    b.Property<int>("TotalFlights")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Registration")
                        .IsUnique();

                    b.ToTable("UserAircrafts");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.AircraftSystemWear", b =>
                {
                    b.HasOne("RealFenixFailures.Domain.Entities.UserAircraft", "UserAircraft")
                        .WithMany("SystemWears")
                        .HasForeignKey("UserAircraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealFenixFailures.Domain.Entities.AircraftWearableSystem", "WearableSystem")
                        .WithMany("Wears")
                        .HasForeignKey("WearableSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserAircraft");

                    b.Navigation("WearableSystem");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FailurePreset", b =>
                {
                    b.HasOne("RealFenixFailures.Domain.Entities.PresetType", null)
                        .WithMany()
                        .HasForeignKey("PresetTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FenixFailureDefinition", b =>
                {
                    b.HasOne("RealFenixFailures.Domain.Entities.FenixFailureGroup", "Group")
                        .WithMany("FailureDefinitions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FenixFailureGroup", b =>
                {
                    b.HasOne("RealFenixFailures.Domain.Entities.FenixFailureSystem", "System")
                        .WithMany("FailureGroups")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("System");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FlightSession", b =>
                {
                    b.HasOne("RealFenixFailures.Domain.Entities.UserAircraft", "UserAircraft")
                        .WithMany("FlightSessions")
                        .HasForeignKey("UserAircraftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserAircraft");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.PresetFailureDefinition", b =>
                {
                    b.HasOne("RealFenixFailures.Domain.Entities.FenixFailureDefinition", "FenixFailure")
                        .WithMany("PresetFailureDefinitions")
                        .HasForeignKey("FenixFailureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RealFenixFailures.Domain.Entities.FailurePreset", "Preset")
                        .WithMany("PresetFailureDefinitions")
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FenixFailure");

                    b.Navigation("Preset");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.TriggeredFailure", b =>
                {
                    b.HasOne("RealFenixFailures.Domain.Entities.FenixFailureDefinition", "FenixFailure")
                        .WithMany()
                        .HasForeignKey("FenixFailureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RealFenixFailures.Domain.Entities.FlightSession", "FlightSession")
                        .WithMany("TriggeredFailures")
                        .HasForeignKey("FlightSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FenixFailure");

                    b.Navigation("FlightSession");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.AircraftWearableSystem", b =>
                {
                    b.Navigation("Wears");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FailurePreset", b =>
                {
                    b.Navigation("PresetFailureDefinitions");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FenixFailureDefinition", b =>
                {
                    b.Navigation("PresetFailureDefinitions");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FenixFailureGroup", b =>
                {
                    b.Navigation("FailureDefinitions");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FenixFailureSystem", b =>
                {
                    b.Navigation("FailureGroups");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FlightSession", b =>
                {
                    b.Navigation("TriggeredFailures");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.UserAircraft", b =>
                {
                    b.Navigation("FlightSessions");

                    b.Navigation("SystemWears");
                });
#pragma warning restore 612, 618
        }
    }
}
