// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RealFenixFailures.Infrastructure.Persistence;

#nullable disable

namespace RealFenixFailures.Infrastructure.Migrations
{
    [DbContext(typeof(RealFenixDbContext))]
    partial class RealFenixDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FailurePreset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightPhase")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("PresetType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PresetTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PresetType");

                    b.Property<string>("TriggerDescription")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PresetTypeId");

                    b.ToTable("FailurePresets", t =>
                        {
                            t.Property("PresetType")
                                .HasColumnName("PresetType1");
                        });
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FenixFailureDefinition", b =>
                {
                    b.Property<string>("FenixFailureId")
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER");

                    b.HasKey("FenixFailureId");

                    b.HasIndex("GroupId");

                    b.ToTable("FenixFailureDefinitions");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FenixFailureGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SystemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SystemId");

                    b.ToTable("FenixFailureGroups");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FenixFailureSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FenixFailureSystems");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FlightSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PresetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PresetId");

                    b.ToTable("FlightSessions");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.PresetFailureDefinition", b =>
                {
                    b.Property<int>("PresetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FenixFailureId")
                        .HasMaxLength(180)
                        .HasColumnType("TEXT");

                    b.Property<string>("Above_Altitude")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("AfterEvent")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("AfterEventSeconds")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Below_Altitude")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ias")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<double>("Probability")
                        .HasColumnType("REAL");

                    b.Property<int?>("ProbabilityGroup")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Time")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("PresetId", "FenixFailureId");

                    b.HasIndex("FenixFailureId");

                    b.ToTable("PresetFailureDefinitions");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.PresetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FailurePresetTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "RealisticMode"
                        },
                        new
                        {
                            Id = 2,
                            Description = "TrainingMode"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Custom"
                        },
                        new
                        {
                            Id = 4,
                            Description = "UserPreset"
                        });
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.TriggeredFailure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FenixFailureId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FlightPhase")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PresetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("TriggeredAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FenixFailureId");

                    b.HasIndex("FlightSessionId");

                    b.HasIndex("PresetId");

                    b.ToTable("TriggeredFailures");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FailurePreset", b =>
                {
                    b.HasOne("RealFenixFailures.Domain.Entities.PresetType", null)
                        .WithMany()
                        .HasForeignKey("PresetTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FenixFailureDefinition", b =>
                {
                    b.HasOne("RealFenixFailures.Domain.Entities.FenixFailureGroup", "Group")
                        .WithMany("FailureDefinitions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FenixFailureGroup", b =>
                {
                    b.HasOne("RealFenixFailures.Domain.Entities.FenixFailureSystem", "System")
                        .WithMany("FailureGroups")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("System");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FlightSession", b =>
                {
                    b.HasOne("RealFenixFailures.Domain.Entities.FailurePreset", "Preset")
                        .WithMany()
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Preset");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.PresetFailureDefinition", b =>
                {
                    b.HasOne("RealFenixFailures.Domain.Entities.FenixFailureDefinition", "FenixFailure")
                        .WithMany("PresetFailureDefinitions")
                        .HasForeignKey("FenixFailureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RealFenixFailures.Domain.Entities.FailurePreset", "Preset")
                        .WithMany("PresetFailureDefinitions")
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FenixFailure");

                    b.Navigation("Preset");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.TriggeredFailure", b =>
                {
                    b.HasOne("RealFenixFailures.Domain.Entities.FenixFailureDefinition", "FenixFailure")
                        .WithMany()
                        .HasForeignKey("FenixFailureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RealFenixFailures.Domain.Entities.FlightSession", "FlightSession")
                        .WithMany("TriggeredFailures")
                        .HasForeignKey("FlightSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RealFenixFailures.Domain.Entities.FailurePreset", "Preset")
                        .WithMany()
                        .HasForeignKey("PresetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FenixFailure");

                    b.Navigation("FlightSession");

                    b.Navigation("Preset");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FailurePreset", b =>
                {
                    b.Navigation("PresetFailureDefinitions");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FenixFailureDefinition", b =>
                {
                    b.Navigation("PresetFailureDefinitions");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FenixFailureGroup", b =>
                {
                    b.Navigation("FailureDefinitions");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FenixFailureSystem", b =>
                {
                    b.Navigation("FailureGroups");
                });

            modelBuilder.Entity("RealFenixFailures.Domain.Entities.FlightSession", b =>
                {
                    b.Navigation("TriggeredFailures");
                });
#pragma warning restore 612, 618
        }
    }
}
